spring:
  application:
    name: agri-contract-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/agri_contract_db
    username: postgres
    password: Virendra@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/agricontract
      database: agric_contract_market
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3
        options:
          temperature: 0.2
          top-p: 0.9

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ramanvgrewal@gmail.com
#    password: sanj noou kfek pdsg
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
